package com.swordfish.chimeroid.app.shared.game.viewmodel

import android.view.KeyEvent
import gg.padkit.inputevents.InputEvent

/**
 * Sends a PadKit [InputEvent.Button] to the active core.
 *
 * Single source of truth for "button event -> core key event" translation. Real touch controls
 * reach this via [GameViewModelTouchControls] with events generated by PadKit's own pointer
 * pipeline; macro buttons (see `GameViewModelMacro`) synthesize the same [InputEvent.Button]
 * type instead of hand-rolling a parallel ACTION_DOWN/ACTION_UP dispatch, so both paths share
 * one implementation and one place to fix/extend key-send behavior.
 */
fun GameViewModelRetroGameView.dispatchButtonEvent(event: InputEvent.Button) {
    val action = if (event.pressed) KeyEvent.ACTION_DOWN else KeyEvent.ACTION_UP
    retroGameView?.sendKeyEvent(action, event.id)
}
